#!/bin/bash

if [ $(id -u) -ne 0 ]; then
  echo error: must run with sudo
  exit 1
fi

root=$(cd $(dirname $0); pwd -P)

tunneluser=appstunnel
echo "Create user '$tunneluser'"
useradd $tunneluser || true
chsh -s /bin/nologin $tunneluser

echo "Generate ssh key"
if [ ! -f /home/$tunneluser/.ssh/id_rsa ]; then
  sudo -u $tunneluser ssh-keygen -q -N "" -t rsa
fi
echo 'vvv   copy to apps'
cat /home/$tunneluser/.ssh/id_rsa.pub
echo '^^^   copy to apps'

ln -sf $root/aztunnel.service /lib/systemd/system/aztunnel.service

systemctl enable aztunnel
systemctl start aztunnel
