#!/bin/bash

set -e
set -o nounset

cd -P "$(dirname "$0")"

image=tmquick
container=tmquick
volume=tmquick

docker build --rm -t $image .

set -x
docker stop $container || true
docker volume inspect $volume >/dev/null || docker volume create $volume
docker create --rm \
  --name $container \
  --publish 548:548 \
  --volume /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket \
  --volume $volume:/data \
  $image
docker start $container

./setpass
