#!/bin/bash

set -e
set -o nounset

IMAGE=up-or-not
CONTAINER=upornot

git submodule update --init --recursive

docker build --rm -t $IMAGE src/upornot

docker rm -f $CONTAINER >&/dev/null || true

exec docker run -d --restart=unless-stopped \
  --name $CONTAINER \
  $IMAGE \
    8.8.8.8 \
    192.168.164.1 \
    192.168.10.1 \
    38.88.204.185
