#!/bin/bash

set -e
set -o nounset

IMAGE="gcr.io/google-containers/cadvisor:v0.36.0"
CONTAINER=cadvisor

ROOT="$(cd "$(dirname "$0")"; pwd -P)"

docker rm -f ${CONTAINER} || true

exec docker run -d --restart=unless-stopped \
  --name ${CONTAINER} \
  -v /:/rootfs:ro \
  -v /var/run:/var/run:ro \
  -v /sys:/sys:ro \
  -v /data/docker:/data/docker:ro \
  -v /dev/disk/:/dev/disk/:ro \
  --privileged \
  --device=/dev/kmsg \
  ${IMAGE}
