#!/bin/bash

set -e
set -o nounset

IMAGE="grafana/grafana:7.5.6"
CONTAINER=grafana

ROOT="$(cd "$(dirname "$0")"; pwd -P)"

docker rm -f ${CONTAINER} || true

exec docker run -d --restart=unless-stopped \
  --name ${CONTAINER} \
  --link prometheus \
  -v ${ROOT}/grafana/provisioning/:/etc/grafana/provisioning/ \
  -v grafana_data:/var/lib/grafana \
  --env-file grafana/config.monitoring \
  ${IMAGE}
