#!/bin/bash
#/ Usage: ./start [--pull]
# Runs https://github.com/Ocawesome101/practice-app-2

set -e

IMAGE=ghcr.io/ocawesome101/practice-app-2:foremost
CONTAINER=ptp

if [ "$1" == "--pull" ]; then
  docker pull "${IMAGE}"
fi

echo stopping the old container...
docker rm -f "${CONTAINER}" || true

echo starting the new container...
docker run \
  --name "${CONTAINER}" \
  -d --restart=unless-stopped \
  -u "$(id -u oliver):$(id -g oliver)" \
  -v /data/oliver/ptp2:/app/db \
  --env TZ=America/Indianapolis \
  "${IMAGE}"
