#!/bin/bash

set -e
set -o nounset

ROOT="$(cd "$(dirname "$0")"; pwd -P)"
. ${ROOT}/.config

mkdir -p ${CERTS_ROOT}

build_image() {
  tar c \
    Dockerfile \
    | docker build --rm -t $CERTBOT_IMAGE -
}

if ! build_image >&/dev/null; then
  echo error building docker image
  exit 1
fi

exec docker run -it --rm \
  -v ${CERTS_ROOT}:/etc/letsencrypt \
  -v ${CONFIG_ROOT}:/etc/extraconfig:ro \
  ${CERTBOT_IMAGE} "$@" --dns-dnsimple-credentials /etc/extraconfig/dnsimple.ini
