#!/bin/bash

set -e
set -o nounset

ROOT="$(cd "$(dirname "$0")"; pwd -P)"
. ${ROOT}/.config

### RUN NGINX
docker rm -f ${CONTAINER} || true

#docker run --name ${CONTAINER} \
#  -d --restart=unless-stopped \
exec docker run --name ${CONTAINER} -it --rm \
  --link gnucash-reports \
  -p 8080:80 \
  -p 8443:443 \
  -v ${CERTS_ROOT}/live/pickardayune.com:/etc/letsencrypt/live/pickardayune.com:ro \
  -v ${CERTS_ROOT}/archive/pickardayune.com:/etc/letsencrypt/archive/pickardayune.com:ro \
  -v ${CONF_DIR}:/etc/nginx/conf.d:ro \
  ${IMAGE} 
