#!/bin/bash

set -e
set -o nounset

cd $(dirname $0)

docker rm -f zerotier >&/dev/null || true

exec docker run -d \
  --restart=unless-stopped \
  --name zerotier \
  --cap-add NET_ADMIN \
  --cap-add SYS_ADMIN \
  --device /dev/net/tun \
  --net host \
  -v zerotier-data:/var/lib/zerotier-one \
  zerotier/zerotier:1.8.6
