#!/bin/bash

set -e
set -o nounset

cd $(dirname $0)

docker build --rm --force-rm -t tiny/zerotier .

docker rm -f zerotier || true

exec docker run -d \
  --restart=unless-stopped \
  --name zerotier \
  --cap-add NET_ADMIN \
  --cap-add SYS_ADMIN \
  --device /dev/net/tun \
  --net host \
  -v zerotier-data:/var/lib/zerotier-one \
  tiny/zerotier
