#!/bin/bash

set -e
set -o nounset

ROOT="$(cd "$(dirname "$0")"; pwd -P)"
SUBMODULE=BetterThanNothingWebInterface
IMAGE=starlink-better-than-nothing-web-interface
CONTAINER=starlink

cd "${ROOT}"
git submodule update --init ${SUBMODULE}
cd ${SUBMODULE}
docker build --rm --force-rm \
  --network=host \
  -t ${IMAGE} \
  .

docker rm -f ${CONTAINER} || true

exec docker run -d --restart=unless-stopped \
  --name ${CONTAINER} \
  --env TZ=US/Eastern \
  ${IMAGE}
